name: First GitHub Actions Workflow

on: [push]

jobs:
  first-job:
    runs-on: self-hosted
    steps:
      - name: Say Hello
        run: echo "✅ Hello from EC2 self-hosted runner!"
      - name: Say Bye
        run: echo "👋 Goodbye from EC2!"

